export const products = [
    {
        id: 1,
        name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleave Shirt Gray",
        category: "Baju",
        price: 30,
        image: "/images/products/baju-2.png",
        isCart: false,
        descriptions: "This shirt feature a vibrant and eye-catching color and solid",
    },
    {
        id: 2,
        name: "Jam Tangan Pria STYLE Clasic cocok Untuk Anak Muda maupun Anak",
        category: "Jam",
        price: 27,
        image: "/images/products/jam-1.png",
        isCart: false,
        descriptions: "Jam keren clasic dengan warna coklat yang elegan membuat anda semakin kece",
    },
    {
        id: 3,
        name: "Sepatu Ventela Clasic Keren - White 40-43 / XL(55-60KG)",
        category: "Sepatu",
        price: 42,
        image: "/images/products/sepatu-3.png",
        isCart: false,
        descriptions: "Sepatu keren dengan warna putih yang menggoda, cocok untuk GAYA GAYA/PAMER",
    },
    {
        id: 4,
        name: "Celana Jeans Terbaru Murah & Keren - / XL(55-60KG)",
        category: "Celana",
        price: 20,
        image: "/images/products/celana-1.png",
        isCart: false,
        descriptions: "Celana Keren Jeans Yang menggoda, Membuat tampilan anda semakin kece",
    },
    {
        id: 5,
        name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleave Shirt Gray",
        category: "Baju",
        price: 30,
        image: "/images/products/baju-4.png",
        isCart: false,
        descriptions: "This shirt feature a vibrant and eye-catching color and solid",
    },
    {
        id: 6,
        name: "Sepatu VENTELA BLACK ORIGIN Original Model Terbaru",
        category: "Sepatu",
        price: 27,
        image: "/images/products/sepatu-1.png",
        isCart: false,
        descriptions: "Jam keren clasic dengan warna coklat yang elegan membuat anda semakin kece",
    },
    {
        id: 7,
        name: "Jam Tangan Clasic Keren & MUrah. CONTITITY - ARMY 40-43",
        category: "Jam",
        price: 42,
        image: "/images/products/jam-2.png",
        isCart: false,
        descriptions: "Sepatu keren dengan warna putih yang menggoda, cocok untuk GAYA GAYA/PAMER",
    },
    {
        id: 8,
        name: "Celana Jeans Terbaru Murah & Keren - / XL(55-60KG)",
        category: "Celana",
        price: 20,
        image: "/images/products/celana-4.png",
        isCart: false,
        descriptions: "Celana Keren Jeans Yang menggoda, Membuat tampilan anda semakin kece",
    },
    {
        id: 9,
        name: "Sepatu VENTELA BLACK ORIGIN Original Model Terbaru",
        category: "Sepatu",
        price: 27,
        image: "/images/products/sepatu-2.png",
        isCart: false,
        descriptions: "Jam keren clasic dengan warna coklat yang elegan membuat anda semakin kece",
    },
    {
        id: 10,
        name: "Jam Tangan Clasic Keren & MUrah. CONTITITY - ARMY 40-43",
        category: "Celana",
        price: 42,
        image: "/images/products/celana-2.png",
        isCart: false,
        descriptions: "Sepatu keren dengan warna putih yang menggoda, cocok untuk GAYA GAYA/PAMER",
    },
    {
        id: 11,
        name: "Jam Tangan Clasic Keren & MUrah. CONTITITY - ARMY 40-43",
        category: "Baju",
        price: 42,
        image: "/images/products/baju-5.png",
        isCart: false,
        descriptions: "Sepatu keren dengan warna putih yang menggoda, cocok untuk GAYA GAYA/PAMER",
    },
    {
        id: 12,
        name: "Celana Jeans Terbaru Murah & Keren - / XL(55-60KG)",
        category: "Baju",
        price: 20,
        image: "/images/products/baju-1.png",
        isCart: false,
        descriptions: "Celana Keren Jeans Yang menggoda, Membuat tampilan anda semakin kece",
    }
]